import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['Sora', 'system-ui', 'sans-serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        serif: ['Sora', 'system-ui', 'sans-serif'],
        editorial: ['Manrope', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        hairline: "hsl(var(--hairline))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        paper: "hsl(var(--paper))",
        "paper-deep": "hsl(var(--paper-deep))",
        "ink-deep": "hsl(var(--ink-deep))",
        gold: "hsl(var(--gold))",
        ink: {
          DEFAULT: "hsl(var(--foreground))",
          soft: "hsl(var(--ink-soft))",
          mute: "hsl(var(--ink-mute))",
          deep: "hsl(var(--ink-deep))",
        },
        online: "hsl(var(--online))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          soft: "hsl(var(--primary-soft))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          soft: "hsl(var(--secondary-soft))",
        },
        bubble: {
          me: "hsl(var(--bubble-me))",
          "me-fg": "hsl(var(--bubble-me-fg))",
          them: "hsl(var(--bubble-them))",
          "them-fg": "hsl(var(--bubble-them-fg))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        ad: {
          bg: "hsl(var(--ad-bg))",
          surface: "hsl(var(--ad-surface))",
          "surface-elev": "hsl(var(--ad-surface-elev))",
          border: "hsl(var(--ad-border))",
          fg: "hsl(var(--ad-fg))",
          "fg-soft": "hsl(var(--ad-fg-soft))",
          "fg-mute": "hsl(var(--ad-fg-mute))",
          magenta: "hsl(var(--ad-magenta))",
          "magenta-soft": "hsl(var(--ad-magenta-soft))",
          violet: "hsl(var(--ad-violet))",
          "violet-soft": "hsl(var(--ad-violet-soft))",
          cyan: "hsl(var(--ad-cyan))",
          gold: "hsl(var(--ad-gold))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        soft: "var(--shadow-soft)",
        nav: "var(--shadow-nav)",
        neon: "var(--shadow-neon)",
        paper: "var(--shadow-paper)",
        edge: "var(--shadow-edge)",
      },
      backgroundImage: {
        warm: "var(--gradient-warm)",
        evening: "var(--gradient-evening)",
        "after-dark": "var(--gradient-after-dark)",
        neon: "var(--gradient-neon)",
        paper: "var(--gradient-paper)",
        ink: "var(--gradient-ink)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { from: { opacity: "0", transform: "translateY(4px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-up": { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
        "typing": { "0%, 100%": { opacity: "0.3", transform: "translateY(0)" }, "50%": { opacity: "1", transform: "translateY(-2px)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-up": "slide-up 0.35s cubic-bezier(0.22, 1, 0.36, 1)",
        "typing": "typing 1.2s ease-in-out infinite",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
